[package]
name = "bajat"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[build]
target = "aarch64-apple-ios-sim"

[build-dependencies]
swift-bridge-build = "0.1"

[lib]
crate-type = ["staticlib"]

[dependencies]
swift-bridge = "0.1"
sled = "0.34"
